import { Property, MarketplaceItem, Lead, Testimonial } from './types';

export const PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    title: 'The Royal Sovereign Oasis',
    developer: 'DLF Premium Estate',
    location: 'Golf Course Road Extension, Sector 54',
    city: 'Gurgaon',
    type: 'Assured Return',
    minInvestment: 75, // in Lakhs
    totalValue: '120 Cr',
    projectedROI: 14.8,
    rentalYield: 8.5,
    appreciationRate: 11.2,
    reraId: 'RERA-HRG-2025-9832',
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
    tagline: '12% Assured Bank-Guaranteed Return with Multi-National Anchored Tenants',
    description: 'A premium grade-A LEED Certified commercial business park featuring world-class tech setups and co-working lounges. Managed by global hospitality partner, ensuring regular high-yielding lease renewals with institutional clients.',
    amenities: ['24/7 Security', 'Executive Helipad', 'Double Heights Lobby', 'Smart Waste Management', 'Premium Concierge Desk'],
    paymentPlan: {
      bookingAmount: '₹5,00,000 (Booking Token)',
      stage1: '35% within 30 days of registration',
      stage2: '65% upon Possession with Assured Returns commencement',
    },
    completionYear: 2027,
    investorJiScore: 9.4,
    scores: { location: 5, builder: 5, rental: 5, growth: 4, liquidity: 4 }
  },
  {
    id: 'prop-2',
    title: 'Worli Skyline Sky-Villas',
    developer: 'Lodha Luxury Group',
    location: 'Worli Sea Face Front',
    city: 'Mumbai',
    type: 'Fractional',
    minInvestment: 50,
    totalValue: '350 Cr',
    projectedROI: 16.2,
    rentalYield: 6.2,
    appreciationRate: 13.5,
    reraId: 'RERA-MUM-2024-1182',
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?auto=format&fit=crop&w=800&q=80',
    tagline: 'Fractional Ownership of Pre-leased 4BHK Sky Mansion Facing the Arabian Sea',
    description: 'Own a structural micro-share in Mumbai\'s most prestigious modern residential development. Already leased to a Fortune-500 Managing Director, establishing steady cashflow combined with sky-high capital appreciation.',
    amenities: ['Infinity Sea-Facing Pool', 'Private Elevator access', 'Cigar Room', 'Biometric Automated Entry', 'Internal Home Cinema'],
    paymentPlan: {
      bookingAmount: '₹2,50,005 (Token Deposit)',
      stage1: '40% upon verified structural fractional token purchase',
      stage2: '60% via structured flexible investment SIP cycles',
    },
    completionYear: 2026,
    investorJiScore: 9.2,
    scores: { location: 5, builder: 5, rental: 4, growth: 5, liquidity: 3 }
  },
  {
    id: 'prop-3',
    title: 'Nandu Smart-Tech Logistic Warehouses',
    developer: 'Embassy Industrial Parks',
    location: 'Chakan Industrial Phase II',
    city: 'Pune',
    type: 'Commercial',
    minInvestment: 95,
    totalValue: '85 Cr',
    projectedROI: 12.5,
    rentalYield: 9.2,
    appreciationRate: 8.5,
    reraId: 'RERA-PNE-2025-0921',
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    tagline: 'High-Demand Cargo & Cold Storage Facility Pre-Leased to leading E-commerce Giant',
    description: 'Fully functional, state-of-the-art cold-chain modern logistics depot. Unmatched long-term double net-lease rental security with inflation-adjusting escalation clauses signed every 36 months.',
    amenities: ['Dock Levelers', 'Industrial Fire Sprinklers', 'High-Load Express Elevators', 'Solar Powered Backups', 'Transit Drivers Dormitory'],
    paymentPlan: {
      bookingAmount: '₹10,00,000 (Express Intent)',
      stage1: '50% within signing SLA contract',
      stage2: '50% within 90 days of registration',
    },
    completionYear: 2026,
    investorJiScore: 8.8,
    scores: { location: 4, builder: 5, rental: 5, growth: 3, liquidity: 4 }
  },
  {
    id: 'prop-4',
    title: 'Serene Wavefront Luxury Estates',
    developer: 'Goa Coastal Spaces',
    location: 'Candolim Beach Front Corridor',
    city: 'Goa',
    type: 'Residential',
    minInvestment: 120,
    totalValue: '180 Cr',
    projectedROI: 18.5,
    rentalYield: 7.8,
    appreciationRate: 15.0,
    reraId: 'RERA-GOA-2025-4521',
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    tagline: 'Fully Managed Private Pool Villas with Premium Short-Term Holiday Rental Syndication',
    description: 'A breath-taking collection of modern Iberian-style boutique villas fully serviced by a 5-star hospitality operator. Benefit from high-occupancy leisure tourist spikes and secure luxury real estate appreciation.',
    amenities: ['Private plunge pools', '24/7 Butler Service', 'Beachfront Club Access', 'State-of-the-art Gym', 'Organic Spa Room'],
    paymentPlan: {
      bookingAmount: '₹5,0,000 (VVIP Allocation)',
      stage1: '30% during plinth completion',
      stage2: '70% staggered over building milestones',
    },
    completionYear: 2028,
    investorJiScore: 9.6,
    scores: { location: 5, builder: 4, rental: 5, growth: 5, liquidity: 4 }
  },
  {
    id: 'prop-5',
    title: 'The Bengaluru Sovereign Smart-Hub',
    developer: 'Prestige Group Innovations',
    location: 'Outer Ring Road (ORR) Near Marathahalli',
    city: 'Bengaluru',
    type: 'Fractional',
    minInvestment: 25,
    totalValue: '95 Cr',
    projectedROI: 13.9,
    rentalYield: 8.9,
    appreciationRate: 9.8,
    reraId: 'RERA-KA-2024-3401',
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    tagline: 'Fractional Retail Tech space with Instant Liquidity Option and Triple-A tenants',
    description: 'Invest fractionally in a state-of-the-art office unit featuring high-speed digital architecture, automated climate zones, and massive open layouts catering to global tech leaders.',
    amenities: ['EV Chargers', 'Rooftop Cafeteria', 'Acoustic Conference Zones', 'Face Recognition Access', 'Biophilic Indoor Parks'],
    paymentPlan: {
      bookingAmount: '₹2,50,000 (Allocation Fee)',
      stage1: '100% full upfront block credit for micro-trust creation',
      stage2: 'N/A (Ready to Earn Rent from Day 1)',
    },
    completionYear: 2025,
    investorJiScore: 8.9,
    scores: { location: 4, builder: 4, rental: 5, growth: 4, liquidity: 5 }
  },
  {
    id: 'prop-6',
    title: 'Prestige Ascent High Rise',
    developer: 'Prestige Group Bangalore',
    location: 'Whitefield Global Tech Zone',
    city: 'Bengaluru',
    type: 'Residential',
    minInvestment: 85,
    totalValue: '210 Cr',
    projectedROI: 11.5,
    rentalYield: 4.5,
    appreciationRate: 9.2,
    reraId: 'RERA-KA-2025-1032',
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80',
    tagline: 'Premium Smart Living Homes Adjacent to Major Cyber Parks',
    description: 'Unparalled tech-integrated ultra spacious flats centered in the heart of Whitefields key corporate center. Perfect for self-occupancy or instant high-profile rental leases for tech leaders.',
    amenities: ['Tennis Clay Courts', 'Smart Home App Control', 'Sewerage Treatment Plant', 'Organic Sky Garden', '24HR Water Grid'],
    paymentPlan: {
      bookingAmount: '₹4,00,000',
      stage1: '25% within 45 Days of Booking',
      stage2: '75% Linked directly to construction progress phases',
    },
    completionYear: 2027,
    investorJiScore: 9.0,
    scores: { location: 4, builder: 5, rental: 3, growth: 4, liquidity: 4 }
  },
  {
    id: 'prop-7',
    title: 'Bhakti Divine enclave - Gated Villa Plots',
    developer: 'Radhe Krishna Colonizers',
    location: 'Raman Reti Road, near ISKCON Temple',
    city: 'Vrindavan',
    type: 'Residential',
    minInvestment: 35,
    totalValue: '45 Cr',
    projectedROI: 17.5,
    rentalYield: 5.5,
    appreciationRate: 14.2,
    reraId: 'RERA-UP-VRN-2025-5591',
    isVerified: true,
    isPlot: true,
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
    tagline: 'Spiritual Luxury Gated Township Plots in Sacred Raman Reti',
    description: 'Premium freehold residential plots inside a 50-acre gated luxury town. Features pure natural air, sweet water grid, private mandir parks, and direct legal title registration.',
    amenities: ['Gated Security', 'Spiritual Satsang Hall', 'Sweet Groundwater Supply', 'Vedic Themed Gardens', 'Wide Concrete Roads'],
    paymentPlan: {
      bookingAmount: '₹2,00,000',
      stage1: '40% on layout agreement signing',
      stage2: '60% during direct registry registration'
    },
    completionYear: 2026,
    investorJiScore: 9.3,
    scores: { location: 5, builder: 4, rental: 4, growth: 5, liquidity: 4 }
  },
  {
    id: 'prop-8',
    title: 'Sovereign Galleria High-Street Shops',
    developer: 'Omaxe Builders India',
    location: 'Sector 79 Commercial Corridor',
    city: 'Faridabad',
    type: 'Commercial',
    minInvestment: 45,
    totalValue: '95 Cr',
    projectedROI: 13.5,
    rentalYield: 8.2,
    appreciationRate: 10.5,
    reraId: 'RERA-HR-FRD-2025-0210',
    isVerified: true,
    isRetail: true,
    image: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?auto=format&fit=crop&w=800&q=80',
    tagline: 'High-visibility retail shops with 3-Year Assured Return & lease guarantee',
    description: 'Breathtaking double height commercial high-street shops in the fastest growing sector of Greater Faridabad. Anchored by major food courts, multiplexes, and hypermarkets.',
    amenities: ['Central Air Conditioning', 'Escalators and High-speed Lifts', '100% Power Backup', 'Basement Parking', 'Fire Suppression Systems'],
    paymentPlan: {
      bookingAmount: '₹3,00,000',
      stage1: '50% within 45 days of booking',
      stage2: '50% on commercial fit-out execution'
    },
    completionYear: 2026,
    investorJiScore: 9.1,
    scores: { location: 4, builder: 5, rental: 5, growth: 4, liquidity: 4 }
  },
  {
    id: 'prop-9',
    title: 'Cyber City Elite Hub - Under Construction',
    developer: 'M3M Premium Sourcing',
    location: 'Golf Course Road Extension',
    city: 'Gurgaon',
    type: 'Commercial',
    minInvestment: 90,
    totalValue: '280 Cr',
    projectedROI: 15.6,
    rentalYield: 9.0,
    appreciationRate: 12.8,
    reraId: 'RERA-HRG-2026-1049',
    isVerified: true,
    isUnderConstruction: true,
    isRetail: true,
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    tagline: 'Premium Corporate Chambers with High appreciation Yield Trajectory',
    description: 'Seize pre-launch pricing on Grade-A virtual corporate offices. Located in high growth economic corridor near major multi-nationals and tech junctions, guaranteeing massive occupancy.',
    amenities: ['Premium Executive Club', 'Sky Lounge Café', 'LEED Platinum Rating', 'Automated Thermal Controls', 'High capacity fiber lines'],
    paymentPlan: {
      bookingAmount: '₹5,00,000',
      stage1: '30% during excavation completion',
      stage2: '70% structured in installment plan linked with slab building'
    },
    completionYear: 2028,
    investorJiScore: 9.5,
    scores: { location: 5, builder: 5, rental: 4, growth: 5, liquidity: 4 }
  },
  {
    id: 'prop-10',
    title: 'Heritage Yamuna Expressway Township Plots',
    developer: 'NDA Developers Private Ltd',
    location: 'Yamuna Expressway Road Sector 25',
    city: 'Mathura',
    type: 'Residential',
    minInvestment: 29,
    totalValue: '60 Cr',
    projectedROI: 18.2,
    rentalYield: 3.5,
    appreciationRate: 16.5,
    reraId: 'RERA-UP-MTR-2025-1102',
    isVerified: true,
    isPlot: true,
    image: 'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?auto=format&fit=crop&w=800&q=80',
    tagline: 'High Appreciation Freehold Land Plots adjacent to Jewar Noida Airport Corridor',
    description: 'Invest in highly appreciating land plots right on the Yamuna Expressway corridor. Rapidly evolving institutional zone near the upcoming Jewar International Airport, direct layout registry.',
    amenities: ['Secured Gated Entry', 'Wide 40ft Pitch Roads', 'Continuous Electricity Grid', 'Pollution Free Green Belts', 'Kids Play Parks'],
    paymentPlan: {
      bookingAmount: '₹1,50,000',
      stage1: '30% within 30 days',
      stage2: '70% upon possession & direct mutation registration'
    },
    completionYear: 2026,
    investorJiScore: 9.1,
    scores: { location: 4, builder: 4, rental: 3, growth: 5, liquidity: 5 }
  },
  {
    id: 'prop-11',
    title: 'Noida Golden IT Square',
    developer: 'Wave Infratech Group',
    location: 'Sector 62 Institutional Zone',
    city: 'Noida',
    type: 'Fractional',
    minInvestment: 40,
    totalValue: '145 Cr',
    projectedROI: 14.2,
    rentalYield: 8.8,
    appreciationRate: 11.5,
    reraId: 'RERA-UP-NDA-2024-9981',
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    tagline: 'Fractional pre-leased corporate IT office block with top global tenants',
    description: 'Frictionless micro-shares in high occupancy commercial tech hub of Noida Sector 62. Secure steady quarterly rental income with a legally backed contract.',
    amenities: ['100% DG Backup', 'Executive Cafeteria', 'Acoustic Meeting Pods', 'Multi-layer Automated Parking', 'Rooftop Sports Arena'],
    paymentPlan: {
      bookingAmount: '₹2,00,000',
      stage1: '50% within 15 days',
      stage2: '50% final assignment deed execution'
    },
    completionYear: 2025,
    investorJiScore: 9.0,
    scores: { location: 5, builder: 4, rental: 5, growth: 4, liquidity: 4 }
  },
  {
    id: 'prop-12',
    title: 'Connaught Royal Business Plaza',
    developer: 'Delhi Construction Corp',
    location: 'Connaught Place Outer Circle Line',
    city: 'Delhi',
    type: 'Assured Return',
    minInvestment: 110,
    totalValue: '480 Cr',
    projectedROI: 15.1,
    rentalYield: 9.5,
    appreciationRate: 10.2,
    reraId: 'RERA-DL-CP-2025-4410',
    isVerified: true,
    isRetail: true,
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80',
    tagline: 'Assured return business lounge pre-leased to top global financial firm',
    description: 'Ultra niche retail and corporate business plaza in Connaught Place, the capital’s most premium commercial zone. Unprecedented 10% assured annual yield with high security.',
    amenities: ['VIP Concierge Desk', 'Helipad Access', 'Thermal insulated building', 'Grand double height atrium', 'High definition telecommunication'],
    paymentPlan: {
      bookingAmount: '₹10,00,000',
      stage1: '40% within 30 days of booking',
      stage2: '60% final registry deed registration'
    },
    completionYear: 2025,
    investorJiScore: 9.7,
    scores: { location: 5, builder: 5, rental: 5, growth: 4, liquidity: 5 }
  },
  {
    id: 'prop-13',
    title: 'Dholera Smart Industrial City (DSIC)',
    developer: 'Dholera Industrial Development Corp',
    location: 'Activation Area, Phase 1 Zone A',
    city: 'Dholera SIR',
    type: 'Commercial',
    minInvestment: 35,
    totalValue: '150 Cr',
    projectedROI: 18.5,
    rentalYield: 7.2,
    appreciationRate: 18.2,
    reraId: 'RERA-GJ-DHL-2025-0012',
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    tagline: 'Industrial and Smart Logistics plots in India’s first Platinum-rated Greenfield Smart City',
    description: 'Highly prized logistics and manufacturing layout in Dholera Special Investment Region (SIR). Features smart ICT trunk infrastructure, direct gas pipeline, 100-meter wide arterial roads, and immediate power connectivity.',
    amenities: ['Trunk Infrastructure', 'High capacity fiber connection', 'Smart waste disposal', 'Underground power cables', '24/7 dedicated fire station'],
    paymentPlan: {
      bookingAmount: '₹2,00,000',
      stage1: '35% within 45 days of booking',
      stage2: '65% upon site earmarking and registry deed handover'
    },
    completionYear: 2026,
    investorJiScore: 9.6,
    scores: { location: 5, builder: 5, rental: 4, growth: 5, liquidity: 5 }
  },
  {
    id: 'prop-14',
    title: 'Dholera Metro Hub Plotted Estate',
    developer: 'GIFT-Dholera Smart Infra',
    location: 'High-speed Rail Corridor Expressway, Sector 3',
    city: 'Dholera SIR',
    type: 'Residential',
    minInvestment: 18,
    totalValue: '40 Cr',
    projectedROI: 21.0,
    rentalYield: 3.0,
    appreciationRate: 22.5,
    reraId: 'RERA-GJ-DHL-2026-0814',
    isVerified: true,
    isPlot: true,
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
    tagline: 'Greenfield high-speed rail corridor freehold plots with premium FSI guidelines',
    description: 'Premium freehold residential land layouts in close proximity to the upcoming Ahmedabad-Dholera High Speed Metro Station. Located in a secured high-grade gated community with wide concrete avenues.',
    amenities: ['Gated security system', 'Concrete internal roads', 'Rainwater harvesting grid', 'Central herbal gardens', 'Solar streetlighting'],
    paymentPlan: {
      bookingAmount: '₹1,00,000',
      stage1: '30% within 30 days',
      stage2: '70% during direct registry registration'
    },
    completionYear: 2027,
    investorJiScore: 9.3,
    scores: { location: 4, builder: 4, rental: 3, growth: 5, liquidity: 5 }
  },
  {
    id: 'prop-15',
    title: 'Aether Greenfield Automated Logistics Park',
    developer: 'Adani Logistics Enterprise',
    location: 'Multi-Modal Sourcing Hub Corridor',
    city: 'Dholera SIR',
    type: 'Assured Return',
    minInvestment: 80,
    totalValue: '340 Cr',
    projectedROI: 15.8,
    rentalYield: 9.5,
    appreciationRate: 12.0,
    reraId: 'RERA-GJ-DHL-2025-1011',
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    tagline: 'Assured rental payouts on highly automated modern warehouse units',
    description: 'High-tech cold-storage and multi-modal logistics hub fully leased to major global shipping and supply chain enterprises. Unrivaled location with immediate proximity to Dholera International Cargo Airport.',
    amenities: ['Automated temperature control', 'Heavy vehicle docking system', 'Seismic resistant pillars', '24HR continuous backups', 'On-site customs clearings desk'],
    paymentPlan: {
      bookingAmount: '₹5,00,000',
      stage1: '40% within 30 days',
      stage2: '60% final possession with direct assured rent payouts activation'
    },
    completionYear: 2026,
    investorJiScore: 9.5,
    scores: { location: 5, builder: 5, rental: 5, growth: 5, liquidity: 4 }
  },
  {
    id: 'prop-16',
    title: 'Gachibowli High-Tech Sourcing Chambers',
    developer: 'My Home Group Real Estate',
    location: 'Financial District Core Road, Gachibowli',
    city: 'Hyderabad',
    type: 'Fractional',
    minInvestment: 40,
    totalValue: '185 Cr',
    projectedROI: 14.2,
    rentalYield: 8.7,
    appreciationRate: 10.8,
    reraId: 'RERA-TS-HYD-2025-0983',
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    tagline: 'Pre-leased tech co-working workspace with instant capital appreciation',
    description: 'Acquire fractional micro-shares of a fully furnished premium tech hub in Hyderabad’s prime IT district. Fully pre-leased to multi-national SaaS organizations with indexation-linked rental hikes.',
    amenities: ['Gigabit internet infrastructure', 'Soundproof meeting pods', 'Premium fitness gym', 'Biometric security locks', 'Central air purification'],
    paymentPlan: {
      bookingAmount: '₹2,00,000',
      stage1: '50% on digital registry',
      stage2: '50% within 30 days of trust deed issuance'
    },
    completionYear: 2025,
    investorJiScore: 9.2,
    scores: { location: 5, builder: 4, rental: 5, growth: 4, liquidity: 4 }
  },
  {
    id: 'prop-17',
    title: 'Jubilee Hills Grand Heritage Manor',
    developer: 'Aurobindo Realty',
    location: 'Elite Residential Hub, Road No 36',
    city: 'Hyderabad',
    type: 'Residential',
    minInvestment: 250,
    totalValue: '420 Cr',
    projectedROI: 15.0,
    rentalYield: 5.2,
    appreciationRate: 14.5,
    reraId: 'RERA-TS-HYD-2026-1180',
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    tagline: 'Ultra-exclusive luxury residential estates in India’s richest neighborhood',
    description: 'A spectacular collection of master-crafted premium villas with bespoke modern architecture, pristine marble finishes, and maximum personal privacy systems in Hyderabad’s most sought-after address.',
    amenities: ['24/7 personal butler', 'Direct private infinity pool', 'Secure air-tight panic room', 'Advanced thermal insulation', 'Exclusive club access card'],
    paymentPlan: {
      bookingAmount: '₹10,00,000',
      stage1: '30% on plinth construction',
      stage2: '70% staggered over building milestones'
    },
    completionYear: 2028,
    investorJiScore: 9.5,
    scores: { location: 5, builder: 5, rental: 3, growth: 5, liquidity: 4 }
  },
  {
    id: 'prop-18',
    title: 'OMR Tech Expressway Towers',
    developer: 'Appaswamy Real Estates',
    location: 'OMR IT Expressway, Sholinganallur',
    city: 'Chennai',
    type: 'Fractional',
    minInvestment: 30,
    totalValue: '125 Cr',
    projectedROI: 13.5,
    rentalYield: 8.4,
    appreciationRate: 9.6,
    reraId: 'RERA-TN-CHN-2025-4491',
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    tagline: 'Pre-leased tech workspaces on Chennai’s premier commercial highway',
    description: 'Acquire high-performing commercial shares in a pristine, state-of-the-art office building occupied by blue-chip international tech conglomerates. Outstanding rental security and yield metrics.',
    amenities: ['Dual grid power supply', 'Premium rooftop dining space', 'Advanced water filtration plant', 'Express capsule elevators', 'EV charging hubs'],
    paymentPlan: {
      bookingAmount: '₹2,50,000',
      stage1: '50% within 15 days of allotment',
      stage2: '50% on final registry'
    },
    completionYear: 2025,
    investorJiScore: 9.0,
    scores: { location: 4, builder: 5, rental: 5, growth: 4, liquidity: 4 }
  },
  {
    id: 'prop-19',
    title: 'ECR Wavefront Coastal Villas',
    developer: 'Casagrand Luxury Homes',
    location: 'ECR Sea Breeze Avenue, Kovalam Corridor',
    city: 'Chennai',
    type: 'Residential',
    minInvestment: 160,
    totalValue: '195 Cr',
    projectedROI: 17.2,
    rentalYield: 6.8,
    appreciationRate: 13.8,
    reraId: 'RERA-TN-CHN-2026-3021',
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
    tagline: 'Premium beachfront vacation villas with high-yield tourist leasing program',
    description: 'An elegant selection of managed vacation retreats on Chennai’s prestigious East Coast Road (ECR). Fully serviced by professional hospitality operators, generating passive short-term rental profits.',
    amenities: ['Private sandy beach access', 'Short-term guest manager desk', 'Sea facing sun terraces', 'Solar heating grid', 'Premium sports club'],
    paymentPlan: {
      bookingAmount: '₹5,00,000',
      stage1: '30% on layout earmarks',
      stage2: '70% staggered over building schedules'
    },
    completionYear: 2027,
    investorJiScore: 9.4,
    scores: { location: 5, builder: 4, rental: 5, growth: 5, liquidity: 4 }
  },
  {
    id: 'prop-20',
    title: 'Salt Lake Sector V Tech Tower',
    developer: 'Srijan Realty Limited',
    location: 'Sector V Commercial Zone',
    city: 'Kolkata',
    type: 'Commercial',
    minInvestment: 55,
    totalValue: '140 Cr',
    projectedROI: 12.8,
    rentalYield: 8.1,
    appreciationRate: 9.0,
    reraId: 'RERA-WB-KOL-2025-2311',
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    tagline: 'High street corporate offices in East India’s chief tech corridor',
    description: 'Fully RERA-approved corporate development located directly on the Sector V main transit hub. Exceptional structural build with double-height showrooms and virtual premium business suites.',
    amenities: ['High-speed internet nodes', 'Central heating and air conditioning', 'Automated energy saving system', 'High security multi-tier gate', 'Multi-level parking lot'],
    paymentPlan: {
      bookingAmount: '₹3,00,000',
      stage1: '50% within 30 days',
      stage2: '50% on final commercial fitout layout handover'
    },
    completionYear: 2026,
    investorJiScore: 8.9,
    scores: { location: 5, builder: 4, rental: 5, growth: 3, liquidity: 4 }
  },
  {
    id: 'prop-21',
    title: 'GIFT City FinTech Sovereign Towers',
    developer: 'Shivalik Group Innovations',
    location: 'FinTech SEZ Zone, GIFT City',
    city: 'Ahmedabad',
    type: 'Assured Return',
    minInvestment: 65,
    totalValue: '290 Cr',
    projectedROI: 16.5,
    rentalYield: 9.0,
    appreciationRate: 13.5,
    reraId: 'RERA-GJ-AHD-2025-8821',
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    tagline: 'Assured yield premium offices inside India’s chief international IFSC financial hub',
    description: 'Invest inside India’s sovereign offshore financial district. Highly prized commercial virtual layouts pre-leased to elite global investment desks, securing 100% tax exemptions and unparalleled returns.',
    amenities: ['IFSC regulatory compliance', 'District cooling system connection', 'Underground utility tunnel access', 'Dual-redundant power backup', 'Ultra-premium conference lounges'],
    paymentPlan: {
      bookingAmount: '₹4,00,000',
      stage1: '40% within 45 days of booking',
      stage2: '60% final registry handover with assured rentals commencing'
    },
    completionYear: 2026,
    investorJiScore: 9.6,
    scores: { location: 5, builder: 5, rental: 5, growth: 5, liquidity: 4 }
  },
  {
    id: 'prop-22',
    title: 'Sabarmati Premium Riverview Suites',
    developer: 'Adani Realty',
    location: 'Sabarmati Riverfront Boulevard',
    city: 'Ahmedabad',
    type: 'Residential',
    minInvestment: 95,
    totalValue: '180 Cr',
    projectedROI: 14.0,
    rentalYield: 5.5,
    appreciationRate: 12.8,
    reraId: 'RERA-GJ-AHD-2026-0044',
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
    tagline: 'Breathtaking riverfront residences with pristine design elements',
    description: 'Premium spacious residential flats with unobstructed panoramic views of the beautiful Sabarmati riverfront. Features Italian imported marble, full smart home automation, and immediate access to key metro lines.',
    amenities: ['Infinity gym overlooking river', 'Intelligent automated lighting', 'Exclusive sky high club', 'EV high speed chargers', 'Double height concierge foyer'],
    paymentPlan: {
      bookingAmount: '₹3,50,000',
      stage1: '30% on plinth completion',
      stage2: '70% staggered across concrete shell works'
    },
    completionYear: 2027,
    investorJiScore: 9.3,
    scores: { location: 5, builder: 4, rental: 4, growth: 5, liquidity: 4 }
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Vikramjit Sahney',
    profile: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    role: 'Managing Director & Angel Investor',
    company: 'Capital Matrix UAE',
    content: 'InvestorJi completely shifted the perspective from standard property hunting to institutional quantitative asset management. I purchased fractional shares in Mumbai Worli Sea Face sky villas, yielding an immediate 6.2% passive rental income, direct and transparent.',
    investmentAmount: '₹1.5 Crores',
    achievedROI: '16.2% IRR'
  },
  {
    id: 'test-2',
    name: 'Dr. Shruti Nair',
    profile: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
    role: 'Retired Senior Neurosurgeon',
    company: 'Fortis Health Global',
    content: 'For NRI professionals like myself, navigating RERA status and development delays used to be terrifying. InvestorJis RERA-verified escrow-based payment plan structure gave me the ultimate safety parameters for peace of mind.',
    investmentAmount: '₹95 Lakhs',
    achievedROI: '14.8% IRR'
  },
  {
    id: 'test-3',
    name: 'Amanpreet Singh',
    profile: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80',
    role: 'Co-Founder',
    company: 'Unicorn Flow India',
    content: 'I highly advise the Real Estate vs SIP tool. It illustrated exactly where to allocate capital to maximize post-tax yields. The construction marketplace is an incredible additional asset, as we sourced our premium Italian marble directly from verified suppliers here!',
    investmentAmount: '₹2.1 Crores',
    achievedROI: '18.5% IRR'
  }
];

export const AGENT_LEADS: Lead[] = [
  {
    id: 'lead-1',
    buyerName: 'Rohan Singhania',
    phonePrefix: '+971 50',
    phoneSuffix: '••• •882',
    city: 'Dubai (NRI)',
    targetLocation: 'Worli Sea Face / Bandra Kurla Complex',
    budget: '₹5 Cr - ₹10 Cr',
    propertyType: 'Fractional, Prime Seaview Sky Villas',
    timeframe: 'Immediate Buying Intent (within 15 days)',
    score: 98,
    isVerified: true,
    price: 1499,
    isPurchased: false,
    dateAdded: '2 hours ago'
  },
  {
    id: 'lead-2',
    buyerName: 'Dr. Amrita Sen',
    phonePrefix: '+91 9845',
    phoneSuffix: '••• •421',
    city: 'Bengaluru',
    targetLocation: 'Whitefield Global Tech Hub, Outer Ring Road',
    budget: '₹1.5 Cr - ₹3 Cr',
    propertyType: 'Co-Living Fractional & Smart High-Yield Hubs',
    timeframe: 'Active investor (looking to deploy surplus funds)',
    score: 93,
    isVerified: true,
    price: 999,
    isPurchased: false,
    dateAdded: '4 hours ago'
  },
  {
    id: 'lead-3',
    buyerName: 'Lt. Col. Sandeep Deshmukh',
    phonePrefix: '+91 7720',
    phoneSuffix: '••• •911',
    city: 'Pune',
    targetLocation: 'Kharadi IT Corridor / Hinjewadi Phase I',
    budget: '₹80 Lakhs - ₹1.5 Cr',
    propertyType: 'Assured Return Premium Commercial Tech Space',
    timeframe: 'Decisive buyer (capital ready via commercial loans)',
    score: 89,
    isVerified: true,
    price: 799,
    isPurchased: false,
    dateAdded: '1 day ago'
  },
  {
    id: 'lead-4',
    buyerName: 'Megha Jha',
    phonePrefix: '+91 9110',
    phoneSuffix: '••• •302',
    city: 'Delhi NCR',
    targetLocation: 'Gurgaon Golf Course Ext. Road',
    budget: '₹2.5 Cr - ₹5 Cr',
    propertyType: 'Grade-A Multi-Tenant Commercial Parks',
    timeframe: 'Looking to purchase 3-4 fractional units',
    score: 96,
    isVerified: true,
    price: 1299,
    isPurchased: false,
    dateAdded: 'Just Now'
  },
  {
    id: 'lead-5',
    buyerName: 'Anshul Singhal',
    phonePrefix: '+91 8890',
    phoneSuffix: '••• •737',
    city: 'Mumbai',
    targetLocation: 'Lower Parel Complex',
    budget: '₹4 Cr - ₹12 Cr',
    propertyType: 'Luxury Premium Residential & Oceanfront Penthouses',
    timeframe: 'Shortlisted selected premium properties',
    score: 92,
    isVerified: true,
    price: 1599,
    isPurchased: false,
    dateAdded: '3 hours ago'
  }
];

export const MARKETPLACE_ITEMS: MarketplaceItem[] = [
  {
    id: 'mkt-1',
    title: 'Italian Statuario Ultra-Premium Polished Marble Slabs',
    category: 'Furnishing',
    brand: 'Marbella Luxury Stones',
    price: 380, // Price in ₹ per Sq. Ft.
    originalPrice: 480,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=400&q=80',
    description: 'Breathtaking pure-white base with defined slate-grey luxury dramatic veins. Direct origin Carrera Tuscany, flawlessly pre-polished for world-class high-end villa flooring.',
    location: 'Mumbai Harbor Yards / Delivery Pan-India',
    isAvailable: true
  },
  {
    id: 'mkt-2',
    title: 'JK Super Strong Concrete Cement (Grade-A Structural)',
    category: 'Construction',
    brand: 'JK Cement Ltd',
    price: 435, // Price in ₹ per Bag (50kg)
    originalPrice: 490,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&w=400&q=80',
    description: 'High-Performance state-of-the-art Portland Pozzolana Cement. Crafted using computerized pre-mixes with high chemical resistance, excellent setting speed, and extreme structural durability.',
    location: 'Sourced directly from JK Authorized Regional Depots',
    isAvailable: true
  },
  {
    id: 'mkt-3',
    title: 'Tata Tiscon Fe 550D High-Stability Reinforcement Steel TMT Rebars',
    category: 'Hardware & Steel',
    brand: 'Tata Steel Infrastructure',
    price: 64500, // Price in ₹ per Ton
    originalPrice: 72000,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=400&q=80',
    description: 'Superior earthquake-resistant high ductility TMT steel bars. Delivers maximum concrete grip due to automated exact ribbing design. Tested raw core quality for multi-story skyscraper construction.',
    location: 'Pan-India Distribution Point Centers',
    isAvailable: true
  },
  {
    id: 'mkt-4',
    title: 'Asian Paints Royale Glitz Luxury Wall Coating with Teflon Protector',
    category: 'Furnishing',
    brand: 'Asian Paints',
    price: 12400, // Price in ₹ per 20L Can
    originalPrice: 14500,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=400&q=80',
    description: 'Ultra-luxurious smooth high sheen finish. Exceptional dirt stain resistance with dynamic Teflon surface protectors. Air purifying properties with non-toxic zero-VOC emissions.',
    location: 'Ready stock in Delhi, Pune, Kolkata, Hyderabad, Bengaluru',
    isAvailable: true
  },
  {
    id: 'mkt-5',
    title: 'Jaquar Luxury Smart Thermostatic Gold Column Shower & Mixer Set',
    category: 'Bath & Sanitary',
    brand: 'Jaquar Artize Premium',
    price: 32500, // Price in ₹
    originalPrice: 45000,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?auto=format&fit=crop&w=400&q=80',
    description: 'Pre-calibrated absolute water-temperature regulator column with anti-scald smart core. Fine brushed gold structural physical vapor deposition (PVD) anti-rust guarantee.',
    location: 'Sourced from authorized Jaquar Enterprise hubs',
    isAvailable: true
  },
  {
    id: 'mkt-6',
    title: 'Havells Sovereign Brass LED Multi-Tier Chandelier Panel with App Control',
    category: 'Electrical & Lighting',
    brand: 'Havells Smart Home',
    price: 18500, // Price in ₹
    originalPrice: 24000,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=400&q=80',
    description: 'Dimmable smart energy-efficient warm light cascades under solid brass fixtures. Control light warmth level, timing rhythms, and smart triggers via major home voice systems.',
    location: 'Ready dispatch centers pan-India',
    isAvailable: true
  }
];
